# Generated by Django 4.2.4 on 2023-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="closed_from",
            field=models.TimeField(default="22:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="closed_until",
            field=models.TimeField(default="8:00"),
            preserve_default=False,
        ),
    ]
